//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project07
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string SNP { get; set; }
        public int YearOfBirth { get; set; }
        public string Address { get; set; }
        public string Faculty { get; set; }
        public string Specialty { get; set; }
        public Nullable<int> Course { get; set; }
    }
}
